
package com.ibm.rules.decisionservice.gbs_rule.gbs_dc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GBS_DCDecisionService", targetNamespace = "http://www.ibm.com/rules/decisionservice/GBS_RULE/GBS_DC")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ibm.rules.decisionservice.gbs_rule.gbs_dc.param.ObjectFactory.class,
    com.ibm.rules.decisionservice.gbs_rule.gbs_dc.ObjectFactory.class
})
public interface GBSDCDecisionService {


    /**
     * 
     * @param gbsDCRequest
     * @return
     *     returns com.ibm.rules.decisionservice.gbs_rule.gbs_dc.GBSDCResponse
     * @throws GBSDCSoapFault
     */
    @WebMethod(operationName = "GBS_DC", action = "GBS_DC")
    @WebResult(name = "GBS_DCResponse", targetNamespace = "http://www.ibm.com/rules/decisionservice/GBS_RULE/GBS_DC", partName = "GBS_DCResponse")
    public GBSDCResponse gbsDC(
        @WebParam(name = "GBS_DCRequest", targetNamespace = "http://www.ibm.com/rules/decisionservice/GBS_RULE/GBS_DC", partName = "GBS_DCRequest")
        GBSDCRequest gbsDCRequest)
        throws GBSDCSoapFault
    ;

}
