
package com.uaf.grtwf.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-02-05T12:37:13.584+08:00
 * Generated source version: 3.0.3
 * 
 */
public final class ApprovalWebService_ApprovalServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.grtwf.uaf.com/", "ApprovalWebService");

    private ApprovalWebService_ApprovalServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ApprovalWebService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ApprovalWebService_Service ss = new ApprovalWebService_Service(wsdlURL, SERVICE_NAME);
        ApprovalWebService port = ss.getApprovalServicePort();  
        
        {
        System.out.println("Invoking claimTask...");
        java.lang.String _claimTask_arg0 = "";
        java.lang.String _claimTask_arg1 = "";
        try {
            port.claimTask(_claimTask_arg0, _claimTask_arg1);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getVariables...");
        java.lang.String _getVariables_arg0 = "";
        try {
            com.uaf.grtwf.webservice.MapEntityArray _getVariables__return = port.getVariables(_getVariables_arg0);
            System.out.println("getVariables.result=" + _getVariables__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking completeTask...");
        java.lang.String _completeTask_arg0 = "";
        java.lang.String _completeTask_arg1 = "";
        com.uaf.grtwf.webservice.MapEntityArray _completeTask_arg2 = null;
        try {
            port.completeTask(_completeTask_arg0, _completeTask_arg1, _completeTask_arg2);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking startProcess...");
        java.lang.String _startProcess_arg0 = "";
        java.lang.String _startProcess_arg1 = "";
        com.uaf.grtwf.webservice.MapEntityArray _startProcess_arg2 = null;
        try {
            java.lang.String _startProcess__return = port.startProcess(_startProcess_arg0, _startProcess_arg1, _startProcess_arg2);
            System.out.println("startProcess.result=" + _startProcess__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking findTodoTasks...");
        java.lang.String _findTodoTasks_arg0 = "";
        java.lang.String _findTodoTasks_arg1 = "";
        try {
            java.util.List<com.uaf.grtwf.webservice.TaskDto> _findTodoTasks__return = port.findTodoTasks(_findTodoTasks_arg0, _findTodoTasks_arg1);
            System.out.println("findTodoTasks.result=" + _findTodoTasks__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
