
package com.uaf.grtwf.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-02-05T12:37:13.653+08:00
 * Generated source version: 3.0.3
 */

@WebFault(name = "Exception", targetNamespace = "http://webservice.grtwf.uaf.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.uaf.grtwf.webservice.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.uaf.grtwf.webservice.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.uaf.grtwf.webservice.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.uaf.grtwf.webservice.Exception getFaultInfo() {
        return this.exception;
    }
}
